# -*- coding: utf-8 -*-
{
    'name': "MATRIX - OBJECT ORIENTED",

    'summary': """
        Matrix model to solve the 2d bidimensional multi cell problem
        generated by the Appointment model. 
    """,

    'description': """

        18 Aug 2019

        For Open Health. New Appointment Module (Object Oriented).

    """,

    'author': "DataMetrics",
    
    'website': "http://jrevilla.com/",
    
    'category': 'Object Oriented',
    
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base'],


    # always loaded
    'data': [
        #'security/ir.model.access.csv',
        #'views/views.xml',
        #'views/templates.xml',
        #'views/matrix_graph.xml',


        #'views/x2m_demo.xml',

        'views/menus.xml',



        'wizard/wizard.xml',

        'views/project.xml',
        'views/user.xml',
        'views/task.xml',
        'views/matrix.xml',


        'views/patient.xml',
        'views/appointment.xml',
        'views/slot.xml',
        'views/container.xml',

        'views/doctor.xml',
        'views/agenda.xml',

    ],



    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],


    # Static - Style Css 
    'css': ['static/src/css/jx.css'],
    
}


